# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gems :
  - jekyll-paginate
  - jekyll-seo-tag
pages_list:
  About: '/about'
  Blog: '/blog'
  Portfolio: '/portfolio'
  Feed: '/atom.xml'

# Setup
title:               Andrew H. Lee
tagline:             'Full Stack Web Developer'
description:         'Welcome to My Site.  Full Stack Web Developer based in Sydney. Always Continuously Learning about Technology & Web Development.'
url:                 http://github.com/andrew-h-lee
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              "Andrew H. Lee"
  linkedin:          "andrewhylee"
  github:            "andrew-h-lee"
  behance:           "andrew-h-lee"
  email:             'mr.ahlee@gmail.com'

# Custom vars
version:             1.0.0

#collection:
#  portfolio:
#    output: true
#    permalink: /portfolio/:path/

#comments:
#  provider               : "disqus"
#  disqus:
#    shortname            : ""

#defaults:
  # _posts
#  - scope:
#      path: ""
#      type: posts
#    values:
#      layout: single
#      author_profile: true
#      comments: true
#      share: true
#      related: true
