# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gems :
  - jekyll-paginate

# Setup
title:               Andrew H. Lee
tagline:             'Full Stack Web Developer'
description:         'Continous Learner'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Andrew H. Lee
  twitter:           'andrew_h_lee'
  email:             'andrew.lee87[at]hotmail[dot]com'
  github:            'andrew-h-lee'
  behance:
  linkedin:

# Custom vars
version:             1.0.0
